pipeline {
    agent any
    stages{
        stage('---clean again---'){
            steps{
                sh "mvn clean"
            }
        }
        stage('---test---'){
            steps{
                sh "mvn test"
            }
        }
        stage('---package---'){
            steps{
                sh "mvn package"
            }
        }
        
}
